export enum RolesEnum {
  ADMINISTRADOR_GENERAL = 1,
  OPS_FINANCIERAS = 2,
  CONTABILIDAD = 3,
  FINANZAS = 4,
  CEO = 5,
  CFO = 6,
  CIBERSEGURIDAD = 7,
  DATOS_MAESTROS = 8,
  HANDLER = 9,
  CARGA = 10,
  CARGA_PAYROLL = 11,
  SUPER_USUARIO = 12,
}
